"""Add ecoindex_version field

Revision ID: 826abb0c4222
Revises: fd9a1f5662c8
Create Date: 2022-09-12 17:39:44.209071

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "826abb0c4222"
down_revision = "fd9a1f5662c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apiecoindex",
        sa.Column(
            "ecoindex_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apiecoindex", "ecoindex_version")
    # ### end Alembic commands ###
