[tool.poetry]
name = "ecoindex_api"
version = "2.3.1"
description = "REST API to expose Ecoindex"
authors = ["Vincent Vatelot <vincent.vatelot@ik.me>"]

[tool.poetry.dependencies]
python = "^3.10"
alembic = "^1.10.1"
celery = "^5.2.7"
ecoindex-scraper = {version = "^2.15.0", allow-prereleases = true}
python-environ = "^0.4.54"
sqlmodel = "^0.0.8"
redis = "^4.5.1"

[tool.poetry.group.api.dependencies]
fastapi = "^0.87.0"
fastapi-health = "^0.4.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
gunicorn = "^20.1.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
aiosqlite = "^0.17.0"
exceptiongroup = "^1.1.0"
Faker = "^15.3.3"
faker-enum = "^0.0.2"
pytest-asyncio = "^0.20.2"
pytest-mock = "^3.9.0"
tomli = "^2.0.1"
typer = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
