[tool.poetry]
name = "ecoindex_api"
version = "0.1.0"
description = "REST API to expose Ecoindex"
authors = ["Vincent Vatelot <vincent.vatelot@ext.adeo.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.68.0"
ecoindex = "^1.6.0"
python-environ = "^0.4.54"
uvicorn = "^0.14.0"
fastapi-pagination = "^0.8.3"
sqlmodel = "^0.0.4"
fastapi-health = "^0.4.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
