[tool.poetry]
name = "ecoindex_api"
version = "0.1.0"
description = "REST API to expose Ecoindex"
authors = ["Vincent Vatelot <vincent.vatelot@ik.me>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.75.2"
ecoindex = {version = "^2.11.0", allow-prereleases = true}
python-environ = "^0.4.54"
uvicorn = "^0.17.5"
sqlmodel = "^0.0.6"
fastapi-health = "^0.4.0"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
black = "^22.3"
aiosqlite = "^0.17.0"
Faker = "^13.4.0"
faker-enum = "^0.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
