[tool.poetry]
name = "ecoindex_api"
version = "1.8.0"
description = "REST API to expose Ecoindex"
authors = ["Vincent Vatelot <vincent.vatelot@ik.me>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.85.0"
python-environ = "^0.4.54"
sqlmodel = "^0.0.7"
fastapi-health = "^0.4.0"
typer = "^0.6.1"
ecoindex-scraper = "^2.4.1"
uvicorn = {extras = ["standard"], version = "^0.18.2"}
gunicorn = "^20.1.0"
alembic = "^1.8.1"

[tool.poetry.dev-dependencies]
black = "^22.3"
aiosqlite = "^0.17.0"
Faker = "^15.1.0"
faker-enum = "^0.0.2"
pytest-asyncio = "^0.19.0"
pytest-mock = "^3.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
