# Build image
FROM python:3.11-slim as requirements-stage

ARG CHROME_VERSION_MAIN=111
ENV CHROMEDRIVER_PATH=/usr/bin/chromedriver

WORKDIR /tmp

# Install required deps
RUN apt update && apt install -y unzip wget
RUN pip install poetry

# Build requirements.txt file
COPY ./pyproject.toml ./poetry.lock /tmp/
RUN poetry export --output=requirements.txt --without-hashes

# Download chromedriver and chrome
RUN wget "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION_MAIN}" -O /tmp/chrome_version
RUN wget "https://chromedriver.storage.googleapis.com/$(cat /tmp/chrome_version)/chromedriver_linux64.zip" && \
    unzip -o chromedriver_linux64.zip && rm chromedriver_linux64.zip
RUN wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_$(cat /tmp/chrome_version)-1_amd64.deb" \
    -O google-chrome-stable.deb

# Main image
FROM python:3.11-slim

ARG CHROME_VERSION_MAIN=111
ENV CHROME_VERSION_MAIN=${CHROME_VERSION_MAIN}
ENV CHROMEDRIVER_PATH=/usr/bin/chromedriver

WORKDIR /code

# Copy requirements.txt, chromedriver, google-chrome-stable.deb from requirements-stage
COPY --from=requirements-stage /tmp/requirements.txt requirements.txt
COPY --from=requirements-stage /tmp/chromedriver ${CHROMEDRIVER_PATH}
COPY --from=requirements-stage /tmp/google-chrome-stable.deb /tmp/

# Install google chrome and make chromedriver executable
RUN apt update && \
    apt -y install libpq-dev gcc /tmp/google-chrome-stable.deb 
RUN chmod +x ${CHROMEDRIVER_PATH}

# Install requirements.txt and install aiomysql
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install aiomysql

# Clean up
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy the rest of the code
COPY ./ /code/

# Copy and execute entrypoint.sh
COPY ./docker/worker/entrypoint.sh /usr/bin/entrypoint
RUN chmod +x /usr/bin/entrypoint

ENTRYPOINT [ "/usr/bin/entrypoint" ]
