name: Update OpenAPI RapidAPI documentation
on:
  push:
    branches:
      - "main"

jobs:
  update-rapidapi-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: RapidAPI OpenAPI
        uses: vvatelot/rapidapi-openapi-github-action@v1.3.4
        with:
          rapidapi-api-key: ${{ secrets.RAPIDAPI_API_KEY }}
          rapidapi-api-id: ${{ secrets.RAPIDAPI_API_ID }}
          default-server-url: ${{ secrets.PROD_DEFAULT_SERVER }}
          openapi-file: "docs/openapi.json"
