name: Update OpenAPI RapidAPI documentation
on:
  schedule:
    # https://crontab.guru/every-night-at-midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request:
    

jobs:
  update-rapidapi-openapi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: RapidAPI OpenAPI
      uses: vvatelot/rapidapi-openapi-github-action@0.0.4
      with:
        rapidapi-api-key: ${{ secrets.RAPIDAPI_API_KEY }}
        rapidapi-api-id: ${{ secrets.RAPIDAPI_API_ID }}
        default-server-url: ${{ secrets.PROD_DEFAULT_SERVER }}
        openapi-file: "docs/openapi.json"